import {
  documentShell,
  escapeHtml,
  renderAuthors,
  renderHead,
  renderWordmark,
} from './html.mjs';

const renderEducation = (entry) => `
      <div class="cv-entry">
        <div class="cv-entry-main">
          <h3>${escapeHtml(entry.institution)}</h3>
          <p>${escapeHtml(entry.degree)}${entry.details ? ` · ${escapeHtml(entry.details)}` : ''}</p>${entry.note ? `
          <p class="cv-note">${escapeHtml(entry.note)}</p>` : ''}
        </div>
        <div class="cv-entry-meta">${escapeHtml(entry.cvDates)}${entry.cvMeta ? ` <span>${escapeHtml(entry.cvMeta)}</span>` : ''}</div>
      </div>`;

const renderExperience = (entry) => `
      <div class="cv-entry">
        <div class="cv-entry-main">
          <h3>${escapeHtml(entry.organization)} · ${escapeHtml(entry.role)}</h3>
          <p class="cv-note">${escapeHtml(entry.description)}</p>
        </div>
        <div class="cv-entry-meta">${escapeHtml(entry.cvDates)} <span>${escapeHtml(entry.location)}</span></div>
      </div>`;

const renderPublication = (publication) => `
        <li>
          <div>${renderAuthors(publication.authors, { abbreviated: true })}. “${escapeHtml(publication.title)}.” <em>${escapeHtml(publication.cvVenue)}.</em></div>${publication.url ? `
          <a href="${escapeHtml(publication.url)}" target="_blank" rel="noreferrer" aria-label="Open ${escapeHtml(publication.title)}">
            <svg viewBox="0 0 16 16" aria-hidden="true">
              <path d="M6 3H3.75A1.75 1.75 0 0 0 2 4.75v7.5C2 13.22 2.78 14 3.75 14h7.5A1.75 1.75 0 0 0 13 12.25V10M9 2h5v5M14 2 7.5 8.5"/>
            </svg>
          </a>` : ''}
        </li>`;

export const renderCv = (content) => {
  const { site, cv, education, experience, publications, service, skills } = content;
  const head = renderHead({
    title: `CV — ${site.name}`,
    description: cv.description,
    cv: true,
  });

  const body = `  <!-- Generated by scripts/build.mjs from content/site.json. -->
  <a class="skip-link" href="#cv-main">Skip to CV</a>
  <header class="site-header scrolled" data-header>
    <div class="nav-wrap">${renderWordmark(site, 'index.html')}
      <div class="cv-nav-actions">
        <a href="index.html">← Back to home</a>
        <button type="button" onclick="window.print()">Print / Save PDF</button>
      </div>
    </div>
  </header>

  <main id="cv-main" class="cv-document">
    <header class="cv-heading">
      <div>
        <p class="cv-kicker">Curriculum Vitae</p>
        <h1>${escapeHtml(site.name)}</h1>
        <p class="cv-title">${escapeHtml(cv.title)}</p>
      </div>
      <address>
        <span>${escapeHtml(site.location)}</span>
        <a href="mailto:${escapeHtml(site.email)}">${escapeHtml(site.email)}</a>
        <a href="${escapeHtml(site.url)}">${escapeHtml(new URL(site.url).host)}</a>
        <a href="${escapeHtml(site.scholar)}">Google Scholar</a>
        <a href="${escapeHtml(site.github)}">${escapeHtml(new URL(site.github).host + new URL(site.github).pathname)}</a>
        <a href="${escapeHtml(site.linkedin)}">LinkedIn</a>
      </address>
    </header>

    <section class="cv-section" aria-labelledby="education-title">
      <h2 id="education-title">Education</h2>${education.map(renderEducation).join('')}
    </section>

    <section class="cv-section" id="publications" aria-labelledby="publications-title">
      <h2 id="publications-title">Publications</h2>
      <ul class="cv-publications">${publications.map(renderPublication).join('')}
      </ul>
    </section>

    <section class="cv-section" aria-labelledby="experience-title">
      <h2 id="experience-title">Professional Experience</h2>${experience.map(renderExperience).join('')}
    </section>

    <section class="cv-section" aria-labelledby="service-title">
      <h2 id="service-title">Professional Service</h2>
      <div class="cv-simple-grid">
        ${service.map((item) => `<p><strong>${escapeHtml(item.role)}</strong><span>${escapeHtml(item.venue)}</span></p>`).join('\n        ')}
      </div>
    </section>

    <section class="cv-section" aria-labelledby="skills-title">
      <h2 id="skills-title">Technical Skills</h2>
      <div class="cv-skills">
        ${skills.map((item) => `<p><strong>${escapeHtml(item.category)}</strong><span>${escapeHtml(item.items)}</span></p>`).join('\n        ')}
      </div>
    </section>

    <footer class="cv-source-note">
      <p>Content synchronized with the <a href="${escapeHtml(site.cvSource)}">version-controlled CV source</a>.</p>
      <p>Last updated ${escapeHtml(site.lastUpdated)}</p>
    </footer>
  </main>`;

  return documentShell({ head, bodyClass: 'cv-page', body });
};
