import {
  documentShell,
  escapeHtml,
  renderAuthors,
  renderHead,
  renderWordmark,
} from './html.mjs';

const renderTimeline = (items, type) => items.map((item) => {
  const title = type === 'education' ? item.institution : item.organization;
  const subtitle = type === 'education' ? item.degree : item.role;
  const meta = type === 'education' ? item.homeMeta : item.location;
  return `
          <article class="timeline-item reveal">
            <div class="timeline-date">${escapeHtml(item.homeDates)}</div>
            <div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(subtitle)}</p><span>${escapeHtml(meta)}</span></div>
          </article>`;
}).join('');

const renderPublication = (publication) => `
          <article class="publication${publication.featured ? ' featured' : ''} reveal">
            <div class="pub-year">${publication.year}</div>
            <div class="pub-body">
              <div class="pub-topline"><span class="venue">${escapeHtml(publication.venue)}</span></div>
              <h3><a href="${escapeHtml(publication.url)}" target="_blank" rel="noreferrer">${escapeHtml(publication.title)} <span aria-hidden="true">↗</span></a></h3>
              <p>${renderAuthors(publication.authors)}</p>
            </div>
          </article>`;

export const renderHome = (content) => {
  const { site, home, education, experience, publications } = content;
  const selectedPublications = publications.filter((publication) => publication.selected);
  const head = renderHead({
    title: home.title,
    description: home.description,
    socialDescription: home.socialDescription,
    url: site.url,
  });

  const body = `  <!-- Generated by scripts/build.mjs from content/site.json. -->
  <a class="skip-link" href="#main">Skip to content</a>

  <header class="site-header" data-header>
    <div class="nav-wrap">${renderWordmark(site, '#top')}
      <button class="menu-button" type="button" aria-expanded="false" aria-controls="site-nav">
        <span></span><span></span><span></span>
        <span class="sr-only">Toggle navigation</span>
      </button>
      <nav id="site-nav" class="site-nav" aria-label="Primary navigation">
        <a href="#about">About</a>
        <a href="#publications">Publications</a>
        <a href="#education">Education</a>
        <a href="#work">Experience</a>
        <a class="nav-cv" href="cv.html">CV <span aria-hidden="true">↗</span></a>
      </nav>
    </div>
  </header>

  <main id="main">
    <section class="hero" id="top">
      <div class="hero-motion" aria-hidden="true">
        <span class="motion-orbit orbit-one"></span>
        <span class="motion-orbit orbit-two"></span>
        <span class="motion-orbit orbit-three"></span>
        <span class="motion-dot dot-one"></span>
        <span class="motion-dot dot-two"></span>
        <span class="motion-dot dot-three"></span>
      </div>
      <div class="hero-grid page-width">
        <div class="hero-copy">
          <p class="eyebrow reveal">${escapeHtml(home.eyebrow)}</p>
          <h1 class="reveal reveal-delay-1">${escapeHtml(home.greeting)} <span class="hero-name">${escapeHtml(site.firstName)}.</span></h1>
          <p class="hero-intro reveal reveal-delay-2">${escapeHtml(home.introduction)}</p>
          <div class="hero-actions reveal reveal-delay-3">
            <a class="button button-primary" href="#publications">View publications <span aria-hidden="true">↓</span></a>
            <a class="button button-quiet" href="cv.html">View full CV <span aria-hidden="true">↗</span></a>
          </div>
          <div class="hero-meta reveal reveal-delay-3" aria-label="Affiliation and location">
            <span>${escapeHtml(home.affiliation)}</span>
            <span>${escapeHtml(site.location)}</span>
          </div>
        </div>
      </div>
    </section>

    <section class="section section-about" id="about">
      <div class="page-width about-grid">
        <div class="section-heading compact reveal">
          <p class="section-index">01 / About</p>
          <h2>${escapeHtml(home.about.heading)}</h2>
        </div>
        <div class="about-copy reveal reveal-delay-1">
          ${home.about.paragraphs.map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`).join('\n          ')}
          <div class="inline-links">
            <a href="mailto:${escapeHtml(site.email)}">Email me <span aria-hidden="true">↗</span></a>
            <a href="${escapeHtml(site.scholar)}" target="_blank" rel="noreferrer">Google Scholar <span aria-hidden="true">↗</span></a>
            <a href="${escapeHtml(site.github)}" target="_blank" rel="noreferrer">GitHub <span aria-hidden="true">↗</span></a>
            <a href="${escapeHtml(site.linkedin)}" target="_blank" rel="noreferrer">LinkedIn <span aria-hidden="true">↗</span></a>
          </div>
        </div>
      </div>
    </section>

    <section class="section section-publications" id="publications">
      <div class="page-width">
        <div class="section-heading row-heading reveal">
          <div><p class="section-index">02 / Publications</p><h2>Selected work</h2></div>
        </div>
        <div class="publication-list">${selectedPublications.map(renderPublication).join('')}
        </div>
        <div class="publication-footer reveal">
          <a class="text-link" href="cv.html#publications">View all publications <span aria-hidden="true">→</span></a>
        </div>
      </div>
    </section>

    <section class="section section-experience" id="education">
      <div class="page-width experience-grid">
        <div class="section-heading compact reveal">
          <p class="section-index">03 / Education</p>
          <h2>Education</h2>
        </div>
        <div class="timeline">${renderTimeline(education, 'education')}
        </div>
      </div>
    </section>

    <section class="section section-work" id="work">
      <div class="page-width experience-grid">
        <div class="section-heading compact reveal">
          <p class="section-index">04 / Work Experience</p>
          <h2>Work experience</h2>
        </div>
        <div class="timeline">${renderTimeline(experience, 'experience')}
        </div>
      </div>
    </section>
  </main>

  <footer class="site-footer">
    <div class="page-width footer-inner">
      <p>© <span data-year>${new Date().getFullYear()}</span> ${escapeHtml(site.name)}</p>
      <p>${escapeHtml(home.footerTagline)}</p>
      <a href="#top">Back to top <span aria-hidden="true">↑</span></a>
    </div>
  </footer>`;

  return documentShell({ head, body });
};
